[DEFAULT]
input_dir = ./csa_data/raw_data
y_col_name = auc
model_name = lgbm
only_cross_study = False
uses_cuda_name = False

csa_outdir = ./LGBM/bruteforce_csa_ccle
source_datasets = ["CCLE"]
target_datasets = ["CCLE"]
split_nums = ["0", "1", "2"]

# Exp full-scale
; csa_outdir = ./bruteforce_csa_full_scale
; source_datasets = ["CCLE", "CTRPv2", "gCSI", "GDSCv1", "GDSCv2"]
; target_datasets = ["CCLE", "CTRPv2", "gCSI", "GDSCv1", "GDSCv2"]
; split_nums = ["0","1","2","3","4","5","6","7","8","9"]

[Preprocess]
data_format = .parquet
y_data_file = response.tsv
cell_transcriptomic_file = cancer_gene_expression.tsv
cell_transcriptomic_transform = [['scale', 'std']]
drug_mordred_file = drug_mordred.tsv
drug_mordred_transform = [['scale', 'std']]

[Train]
data_format = .parquet
model_file_name = model
model_file_format = .txt
epochs = 100
learning_rate = 0.05
#batch_size = None
#val_batch = None
#loss = None
#early_stop_metric = None
patience = 50
n_estimators = 800

[Infer]
data_format = .parquet
model_file_name = model
model_file_format = .txt