[Global_Params]
model_name = LGBM

[Preprocess]
train_split_file = CCLE_split_0_train.txt
val_split_file = CCLE_split_0_val.txt
test_split_file = CCLE_split_0_test.txt
data_format = .parquet
y_data_file = response.tsv
cell_transcriptomic_file = cancer_gene_expression.tsv
cell_transcriptomic_transform = [['scale', 'std']]
drug_mordred_file = drug_mordred.tsv
drug_mordred_transform = [['scale', 'std']]

[Train]
data_format = .parquet
model_file_name = model
model_file_format = .txt
epochs = 100
learning_rate = 0.05
#batch_size = None
#val_batch = None
#loss = None
#early_stop_metric = None
patience = 50
n_estimators = 800


[Infer]
data_format = .parquet
model_file_name = model
model_file_format = .txt